# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-24 11:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Links',
            new_name='Link',
        ),
        migrations.RenameModel(
            old_name='Votes',
            new_name='Vote',
        ),
        migrations.AlterModelOptions(
            name='link',
            options={},
        ),
        migrations.AlterModelOptions(
            name='vote',
            options={},
        ),
    ]
