# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-27 16:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0003_userprofile'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='link',
            managers=[
            ],
        ),
    ]
